// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetQuality():Promise<string>;

export function GetStreamStatus():Promise<main.StreamStatus>;

export function OpenFileDialog():Promise<string>;

export function SetAutoStopOnEnd(arg1:boolean):Promise<void>;

export function SetQuality(arg1:string):Promise<void>;

export function SetWindowAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;

export function StartStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopStream():Promise<void>;
