// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetQuality() {
  return window['go']['main']['App']['GetQuality']();
}

export function GetStreamStatus() {
  return window['go']['main']['App']['GetStreamStatus']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SetAutoStopOnEnd(arg1) {
  return window['go']['main']['App']['SetAutoStopOnEnd'](arg1);
}

export function SetQuality(arg1) {
  return window['go']['main']['App']['SetQuality'](arg1);
}

export function SetWindowAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetWindowAlwaysOnTop'](arg1);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}

export function StartStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartStream'](arg1, arg2, arg3);
}

export function StopStream() {
  return window['go']['main']['App']['StopStream']();
}
